version: '3.8'
services:
  db:
    image: postgres:16
    container_name: mpmt-postgres
    environment:
      POSTGRES_DB: mpmt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: motdepasse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: mpmt-backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mpmt
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: motdepasse
    depends_on:
      - db

volumes:
  postgres_data:
